source ~/.config/vim/settings.vim
source ~/.config/vim/mappings.vim
source ~/.config/vim/autocmd.vim
source ~/.config/vim/quickfix.vim
source ~/.config/vim/statusline.vim

" cat vim/settings.vim vim/statusline.vim vim/mappings.vim vim/autocmd.vim
" vim/autocmd.vim vim/quickfix.vim
