"  _     ___   ____  _   _     _      _   _   _   ___   __ 
" | |_/ | |_) | |_  | |\/||   \ \  / | | | |\/|| | |_) / /`
" |_| \ |_| \ |_|__ |_|  |/    \_\/  |_| |_|  |/ |_| \ \_\_,
"
source ~/.config/vim/settings.vim
source ~/.config/vim/statusline.vim
source ~/.config/vim/mappings.vim
source ~/.config/vim/autocmd.vim
source ~/.config/vim/quickfix.vim

" CONCATENATE
" cat vim/settings.vim vim/statusline.vim vim/mappings.vim vim/autocmd.vim vim/quickfix.vim > vimrc_merged
