background {
    monitor =
    path = color
    color = rgba(35, 32, 54, 1)
    # blur_passes = 10
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(83a6f2ee)
    check_color=rgba(ff9e64ee)
    fail_color=rgba(f7768eee)

    font_color = rgb(c0caf5)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

# vim: set filetype=hyprlang:
