#!/bin/env bash
# centrazed all the tmux conf

function tmuxMain() {
	# exit if tmux is not installed
	which tmux &>/dev/null
	if [[ $? -ne 0 ]]; then
		return
	fi

	# check if inside of tmux
	if [[ -n $TMUX ]]; then
		# inside of tmux
		refreshClient
		echo "enable tmux client refresh"

		setTmuxPrompt
		echo "set tmux prompt"
	else
		# not inside of tmux
		openSession
		echo "opened session"
	fi

	unset -f tmuxMain # forget the function
}

function openSession() {
	tmux list-sessions &>/dev/null
	local session="$?"
	local clients=$(tmux list-clients)

	if [[ $session -eq 0 ]]; then # if their is a session
		if [[ -z $clients ]]; then # but no clients attached
			tmux attach
		fi
	else
		tmux new-session # this is no session
	fi
	unset -f openSession # forget the function
}

function refreshClient() {
	cd() { # each use of 'cd' refreshed the topbar
		builtin cd "$@" && tmux refresh-client -S
	}

	# if zoxide is in use, tmux is refreshed as well
	which zoxide &>/dev/null
	if [[ $? -eq 0 ]]; then
		z() {
			__zoxide_z "$@" && tmux refresh-client -S
		}
	fi
	unset -f refreshClient # forget the function
}

function setTmuxPrompt() {
	PS1='\[\e[38;5;153;1m\] \[\e[0m\]'
	unset -f setTmuxPrompt # forget the function
}

tmuxMain
