#!/bin/env bash
#
# Basic color support
if [[ "$TERM" == *"-256color" ]]; then
	alias ip='ip -c'
	alias grep='grep --color=auto'
	alias ls="ls --color=always"

	# replace cat with bat
	if which bat &>/dev/null; then
		alias cat="bat -pp --theme OneHalfDark"
	fi
fi

# Standard aliases
alias ll="ls -al"
alias vim="$EDITOR"
alias nano="$EDITOR"
alias ..="cd .."
alias c="clear"

# git
alias g="git"
alias st="git status"
alias gd="git diff HEAD"

# docker
alias dcu="docker compose up -d --build && docker compose logs -f"
alias d="docker"

alias tf=tofu
alias getdl="mv  ~/Downloads/\"\$(ls --color=never -trh ~/Downloads/ | tail -1)\""
