# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines
HISTCONTROL=ignoredups

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=1000 # max history size per session
HISTFILESIZE=10000 # max history file size

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
	ip=$(\ip route get 1.1.1.1 2>/dev/null | awk '{ print $7 }')
	if [[ -z $ip ]]; then
		ip=$(hostname)
	fi
	PS1='\[\e[38;5;63;1m\][\[\e[0;38;5;216m\]\u\[\e[38;5;63;1m\]@\[\e[0;38;5;216m\]$ip\[\e[38;5;63;1m\]]–(\[\e[0;97m\]\W\[\e[38;5;63;1m\])\[\e[0;97m\]\$\[\e[97m\] \[\e[0m\]'
fi

unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm|rxvt*|linux)
	# [user@hostname](dir)$ 
	PS1='\[\e[0m\][\[\e[38;5;43;1m\]\u\[\e[0m\]@\[\e[38;5;43;1m\]\h\[\e[0m\]](\[\e[97m\]\W\[\e[0m\])\[\e[97m\]\$ '
    ;;
*)
    ;;
esac

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

###	EXPORTS	###

export LIBVIRT_DEFAULT_URI="qemu:///system"
export PROMPT_COMMAND='history -a; history -n'

# pick the best possible editor
if which nvim &>/dev/null; then
	export EDITOR=nvim
elif which vim &>/dev/null; then
	export EDITOR=vim
elif which vi &>/dev/null; then
	export EDITOR=vi
fi

function addToPath() {
	[[ ! -d "$1" ]] && return 1	# dir must exist
	[[ $PATH == *"$1"* ]] && return 1	# dir must not already be in path

	export PATH=$PATH:$1
	return 0
}
addToPath "$HOME/scripts"
addToPath "$HOME/scripts/utils"

unset -f addToPath

### SOURCE ###

# source ~/.config/bash/.env

# source aliases and functions at the end
function sourceFile() {
	[[ ! -f "$1" ]] && return # $1 must be a valid file
	source "$1"
}

sourceFile "$HOME/.config/bash/bash_tmux.sh"
sourceFile "$HOME/.config/bash/bash_aliases"

if which fzf &>/dev/null; then
	# trying to source the lightweight file
	sourceFile "$HOME/.config/bash/fzf_history.sh"
	if [[ $? -ne 0 ]]; then # else, running the whole script
		eval "$(fzf --bash)"
	fi
fi

unset -f sourceFile

### EVAL ###
if which zoxide &>/dev/null; then
	eval "$(zoxide init bash)"
fi

# remap capslock to ctrl
if [[ $XDG_SESSION_TYPE == "x11" ]]; then
	setxkbmap -option caps:ctrl_modifier
fi
